Repository CougarCS/CougarCS-Client, pull requests merged in 2021-09, with the labels that each got.

#269 Windows Compile Error
  .eslintrc.js
  .eslintrc.json
Labels: enhancement, good first issue

#273 Added GitHub Icon
  src/assets/icons/github.webp
  src/components/Footer/Footer.js
Labels: enhancement

#280 Pushing Updates to Production
  .eslintrc.js
  .eslintrc.json
  src/assets/icons/github.webp
  src/components/ContactForm/ContactForm.js
  src/components/Footer/Footer.js
Labels: release
