Repository CougarCS/CougarCS-Client, pull requests merged in 2021-06, with the labels that each got.

#180 Tutoring Page
  src/App.js
  src/assets/icons/discord-icon.png
  src/assets/tutoring.svg
  src/components/Navbar/Navbar.js
  src/index.css
  src/pages/About/About.css
  src/pages/About/About.js
  src/pages/Tutoring/Tutoring.css
  src/pages/Tutoring/Tutoring.js
Labels: enhancement

#187 Deploying Tutoring Page and Package Upgrades
  src/App.js
  src/assets/icons/discord-icon.png
  src/assets/tutoring.svg
  src/components/Navbar/Navbar.js
  src/index.css
  src/pages/About/About.css
  src/pages/About/About.js
  src/pages/Tutoring/Tutoring.css
  src/pages/Tutoring/Tutoring.js
  yarn.lock
Labels: enhancement

#191 Update README with Testing details
  .gitignore
  README.md
  package.json
Labels: enhancement

#193 Request Tutor Data from Backend
  src/pages/Tutoring/Tutoring.js
Labels: enhancement

#195 Update Tutoring fetching using react-query and added Loading
  src/components/Loading/Loading.css
  src/components/Loading/Loading.js
  src/pages/Events/Event.css
  src/pages/Tutoring/Tutoring.css
  src/pages/Tutoring/Tutoring.js
Labels: enhancement

#201 Events changes to prod
  .github/workflows/cd.yml
  package.json
  public/sitemap.xml
  src/components/AddToCalendar/AddToCalendar.js
  src/components/ContactForm/ContactForm.js
  src/components/Loading/Loading.css
  src/components/Loading/Loading.js
  src/components/Payment/Payment.js
  src/pages/Events/Event.css
  src/pages/Events/Events.js
  src/pages/Tutoring/Tutoring.css
  src/pages/Tutoring/Tutoring.js
  yarn.lock
Labels: enhancement

#203 README and Github Action
  .github/workflows/cd.yml
  README.md
Labels: enhancement

#205 Update Github Action to PROD
  .github/workflows/cd.yml
  README.md
Labels: documentation

#208 403 fix for Gallery
  package.json
  public/sitemap.xml
  src/App.js
  src/components/Footer/Footer.js
  src/components/Payment/Payment.js
  src/pages/Events/Event.css
  src/pages/Gallery/Gallery.js
  src/pages/Policy/Privacy.js
  yarn.lock
Labels: bug
