Repository CougarCS/CougarCS-Client, pull requests merged in 2021-08, with the labels that each got.

#224 Updates to tutoring page
  src/pages/Tutoring/Tutoring.js
Labels: enhancement, update

#230 [DEP] Update dependencies
  package.json
  yarn.lock
Labels: dependencies, update

#223 Replace classification field with shirt size
  src/components/Payment/Payment.js
Labels: enhancement

#234 Release: Registration Page CougarCS Cloud Integration
  src/components/Payment/Payment.js
Labels: update

#242 Replace React Script with Craco
  .eslintignore
  .github/workflows/cd.yml
  craco.config.js
  package.json
  yarn.lock
Labels: enhancement
